apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-example
spec:
  selector:
    matchLabels:
      app: my-first-app
  template:
    metadata:
      labels:
          app: my-first-app
    spec:
      containers:
      - name: example1
        image: springcommunity/spring-framework-petclinic
        ports:
        - containerPort: 8080
